# Generated by Django 6.0.1 on 2026-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(blank=True, max_length=100)),
                ('arquivo_original', models.FileField(upload_to='musicas/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
