# Generated by Django 6.0.1 on 2026-01-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='faixa_baixo',
            field=models.FileField(blank=True, null=True, upload_to='processados/'),
        ),
        migrations.AddField(
            model_name='musica',
            name='faixa_bateria',
            field=models.FileField(blank=True, null=True, upload_to='processados/'),
        ),
        migrations.AddField(
            model_name='musica',
            name='faixa_outros',
            field=models.FileField(blank=True, null=True, upload_to='processados/'),
        ),
        migrations.AddField(
            model_name='musica',
            name='faixa_voz',
            field=models.FileField(blank=True, null=True, upload_to='processados/'),
        ),
    ]
